import { useState } from "react";
import { useLocation } from "wouter";
import { Upload, FileJson, AlertTriangle } from "lucide-react";
import { useImportBundle, Bundle } from "@workspace/api-client-react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { useQueryClient } from "@tanstack/react-query";

const MAX_BUNDLE_BYTES = 256 * 1024;

function errorMessage(error: unknown): string {
  if (typeof error === "object" && error !== null) {
    const data = "data" in error ? error.data : undefined;
    if (
      typeof data === "object" &&
      data !== null &&
      "error" in data &&
      typeof data.error === "string"
    ) {
      return data.error;
    }
    if ("message" in error && typeof error.message === "string") {
      return error.message;
    }
  }
  return "The bundle could not be imported.";
}

export function ImportBundle() {
  const [, setLocation] = useLocation();
  const importBundle = useImportBundle();
  const queryClient = useQueryClient();
  const [error, setError] = useState<string | null>(null);
  const [isParsing, setIsParsing] = useState(false);

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setError(null);
    setIsParsing(true);

    try {
      if (file.size > MAX_BUNDLE_BYTES) {
        throw new Error("Bundle exceeds the 256 KiB import limit.");
      }
      const text = await file.text();
      const data = JSON.parse(text) as Bundle;

      if (!data.format || !data.contract || !data.run) {
        throw new Error("Invalid bundle schema: missing required fields");
      }

      importBundle.mutate(
        {
          data,
        },
        {
          onSuccess: (run) => {
            queryClient.invalidateQueries({ queryKey: ["/api/runs"] });
            setLocation(`/runs/${run.id}`);
          },
          onError: (err: unknown) => {
            setError(errorMessage(err));
          },
        },
      );
    } catch (err: unknown) {
      setError(errorMessage(err));
    } finally {
      setIsParsing(false);
      e.target.value = "";
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-2 border-b border-border pb-4">
        <div className="flex items-center gap-3">
          <Upload className="h-8 w-8 text-primary" />
          <h1 className="text-3xl font-black tracking-tight font-sans uppercase">
            Import Bundle
          </h1>
        </div>
        <p className="text-muted-foreground font-mono text-sm max-w-3xl">
          Load self-reported external execution results for analysis. Imports
          are bounded and preserved as data-only, but are not authenticated or
          certified by Gauntlet.
        </p>
      </div>

      <Card className="rounded-none border-border/50 shadow-none bg-card/50 max-w-2xl">
        <CardHeader className="border-b border-border/50 pb-4">
          <CardTitle className="flex items-center gap-2 text-lg uppercase font-bold tracking-wider">
            <FileJson className="h-5 w-5 text-primary" />
            JSON Bundle
          </CardTitle>
          <CardDescription className="font-mono text-xs">
            Select a .json bundle file generated by a compliant runner.
          </CardDescription>
        </CardHeader>
        <CardContent className="pt-6 space-y-6">
          {error && (
            <div className="p-4 bg-destructive/10 border-l-2 border-destructive flex items-start gap-3">
              <AlertTriangle className="h-4 w-4 text-destructive shrink-0 mt-0.5" />
              <div className="font-mono text-xs text-destructive break-all">
                {error}
              </div>
            </div>
          )}

          <div className="border-2 border-dashed border-border/50 p-12 text-center flex flex-col items-center justify-center relative hover:border-primary/50 transition-colors">
            <input
              type="file"
              accept=".json"
              className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
              onChange={handleFileChange}
              disabled={isParsing || importBundle.isPending}
            />
            <FileJson className="h-10 w-10 text-muted-foreground mb-4 opacity-50" />
            <h3 className="font-mono font-bold uppercase tracking-widest text-sm mb-1">
              Upload Bundle
            </h3>
            <p className="font-mono text-xs text-muted-foreground">
              Click or drag a .json file here
            </p>

            {(isParsing || importBundle.isPending) && (
              <div className="mt-4 font-mono text-xs text-primary animate-pulse uppercase tracking-widest">
                Processing...
              </div>
            )}
          </div>

          <div className="p-4 bg-muted/20 border-l-2 border-muted-foreground/30 font-mono text-[10px] text-muted-foreground">
            <p className="uppercase tracking-widest mb-1 text-foreground">
              Security Note
            </p>
            <p>
              Bundles are parsed locally and transmitted as data-only. URL
              bindings and command instructions are rejected, never executed.
              Canonical vectors and outcomes are independently checked, but the
              external execution claim remains self-reported. Maximum size: 256
              KiB.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
